version: '2'
services:
    broker:
        build: ./broker
        working_dir: /broker
        container_name: broker
        ports:
        - 8883:8883
        volumes:
        - ./broker:/broker
        - ./sub:/sub
        - ./pub:/pub
        - ./certs:/certs
        command: /broker/run.sh
    sub:
        links:
        - broker
        build: ./sub
        working_dir: /sub
        environment:
        - SUB_PORT=8883
        volumes:
        - ./sub:/sub
        - ./certs:/certs
        command: /sub/run.sh
    pub:
        links:
        - broker
        build: ./pub
        working_dir: /pub
        environment:
        - PUB_PORT=8883
        volumes:
        - ./pub:/pub
        - ./certs:/certs
        command: /pub/run.sh
